# Schema for the configuration files of the Escort module.

escort.escort.*:
  type: config_entity
  label: 'Escort config'
  mapping:
    id:
      type: string
      label: 'ID'
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: escort.settings.[%parent.plugin]
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'
    uuid:
      type: string

escort.settings.*:
  type: escort_settings
