# Schema for the configuration files of the Escort module.

escort.escort.*:
  type: config_entity
  label: 'Escort config'
  mapping:
    id:
      type: string
      label: 'ID'
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: escort.settings.[%parent.plugin]
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'
    uuid:
      type: string

escort.settings.*:
  type: escort_settings

escort_settings:
  type: mapping
  label: 'Escort Item settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Description'
    label_display:
      type: string
      label: 'Display title'
    status:
      type: boolean
      label: 'Status'
    info:
      type: label
      label: 'Admin info'
    view_mode:
      type: string
      label: 'View mode'
    provider:
      type: string
      label: 'Provider'
    context_mapping:
      type: sequence
      label: 'Context assignments'
      sequence:
        type: string
